### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Bishal-Sarker** [debajyotikarmaker/cvpr_4234#17]

**Comment by X-AVI-X** [comment]
Please specify your question what you really want to do. If you are trying to load your dataset from your google drive then you have to mount your drive in your notebook. There is a little chunk of code available in the documentation on "google drive mount from jupyter notebook". You can check it out.

If you are talking about utils like keras utils or numpy utils you can simply download it using pip command in your notebook like "pip install keras.utils".

**Comment by Bishal-Sarker** [comment]
nevermind i got the solution, thanks for your kind reply.
