### ISSUE TITLE
YML file names

### ISSUE THREAD

**Issue by snigdho611** [debajyotikarmaker/cvpr_4234#5]
I have already created a pull request with the appropriate changes. 

Its a simple one, original installation file said:
<i>"conda env update --file ./resources/install/cvpr.yml"</i>

I have updated it to this in order to match the correct file names:
<i>"conda env update --file ./resources/install/lib_cpu.yml"</i>
<i>"conda env update --file ./resources/install/lib_gpu.yml"</i>

**Comment by debajyotikarmaker** [comment]
Thanks

**Comment by snigdho611** [comment]
You are welcome, sir.
